### ISSUE TITLE
Creating report-based template without report

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-emailtemplates#16]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3081-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

**TC:**
1. Open attached project -> run app
2. Open Email templates browser ->  Create new report-based template
3. Set name and code ->  Save

AR:
Template is saved

ER:
Field `Report template to generate body` should be required

[simple-sales-jmix.zip](https://github.com/Haulmont/jmix-emailtemplates/files/6676267/simple-sales-jmix.zip)

**Comment by gorbunkov** [comment]
Maybe it will be better to make the *Report template to generate body* combo-box required if the email template editor is opened by the *Create new report-based template* action.
