### ISSUE TITLE
Group value has not been removed from template/block after group removing

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-emailtemplates#18]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3081-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

**TC:**
1. Open attached project -> run app
2. Open email templates browser -> Groups 
3. Create new group TestGroup -> Save
4. Open email templates browser -> create new designer-based template
5. Choose group TestGroup in dropdown  -> Save
6. Open email templates browser -> Groups -> remove TestGroup 
7. Open email templates browser

**AR:**
group is still displayed:
![image](https://user-images.githubusercontent.com/45730069/122754294-899a6a80-d2a4-11eb-818c-939fb7763122.png)
![image](https://user-images.githubusercontent.com/45730069/122754306-8ef7b500-d2a4-11eb-818e-852b98028eaa.png)

the same situation with blocks groups

[simple-sales-jmix.zip](https://github.com/Haulmont/jmix-emailtemplates/files/6676267/simple-sales-jmix.zip)

**Comment by gorbunkov** [comment]
Probably we need to add the `UNLINK` delete policy
